language: python

python:
  - 3.6

install:
  - pip install -r requirements.txt

before_script:
  - sudo redis-server /etc/redis/redis.conf --port 6379

script:
  - touch .env
  - ls *.py */**.py | xargs -n1 pycodestyle --ignore=E501
  - py.test tests/
