language: python

python:
  - 3.6

install:
  - pip install -r requirements.txt

services:
  - postgresql

before_script:
  - sudo redis-server /etc/redis/redis.conf --port 6379
  - psql -f migrate.sql -U postgres

script:
  - touch .env
  - ls *.py */**.py | xargs -n1 pycodestyle --ignore=E501
  - python init_user.py
  - py.test tests/
